apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-pv
  namespace: quizstar
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/quizstar/django-app