apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  namespace: quizstar
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi