version: 0.2
env:
  variables:
    DOCKER_USERNAME: "sahilphule0710"
    IMAGE_NAME: "django-app"
    IMAGE_TAG: "latest"
    DOCKER_PASSWORD: "Sahil@2003"
    
phases:
  pre_build:
    commands:
    - echo logging into dockerhub
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
    - echo build started on `date`
    - echo building the docker image...
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./django-app
    - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
    - echo build completed on `data`
    - echo pushing the docker image...
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG