version: 0.2
phases:
  pre_build:
    commands:
    - echo logging into dockerhub
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
    - echo build started on `date`
    - echo building the docker image $IMAGE_NAME1 ...
    - docker build -t $IMAGE_NAME1:$IMAGE_TAG ./django-app
    - docker tag $IMAGE_NAME1:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME1:$IMAGE_TAG
    - echo building the docker image $IMAGE_NAME2 ...
    - docker build -t $IMAGE_NAME2:$IMAGE_TAG ./nginx
    - docker tag $IMAGE_NAME2:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME2:$IMAGE_TAG
  post_build:
    commands:
    - echo builds completed on `data`
    - echo pushing the docker images to dockerhub ...
    - docker push $DOCKER_USERNAME/$IMAGE_NAME1:$IMAGE_TAG
    - docker push $DOCKER_USERNAME/$IMAGE_NAME2:$IMAGE_TAG