services:
  mysql:
    image: mysql
    container_name: mysql-service
    restart: always
    volumes:
    - ./django-app/data:/var/lib/mysql
    env_file:
    - ./.env

  django-app:
    image: sahilphule0710/django-app
    # build:
    #   context: ./django-app
    #   dockerfile: dockerfile
    container_name: django-app-service
    command: ['/bin/sh','./entrypoint.sh']
    restart: always
    volumes:
    - ./django-app:/django-app
    env_file:
    - ./.env
    ports:
    - 8000:8000
    depends_on:
    - mysql

  nginx:
    image: nginx
    container_name: nginx-service
    restart: always
    volumes:
    - ./django-app:/django-app
    ports:
    - 80:80
    depends_on:
    - django-app

  # redis:
  #   image: redis
  #   container_name: redis-service
  #   restart: always

  # celery:
  #   image: sahilphule0710/django-app
  #   container_name: celery-service
  #   command: celery -A core worker -l INFO
  #   restart: always
  #   volumes:
  #   - ./django-app:/django-app
  #   depends_on:
  #   - django-app
  #   - redis
  
  # celery_beat:
  #   image: sahilphule0710/django-app
  #   container_name: celery-beat-service
  #   command: celery -A core beat -l info
  #   restart: always
  #   volumes:
  #   - ./django-app:/django-app
  #   depends_on:
  #   - celery