apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: quizstar
spec:
  type: NodePort
  selector:
    pod: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30008