apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: quizstar
  labels:
    pod: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: nginx
  template:
    metadata:
      labels:
        pod: nginx
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: nginx-container
        image: sahilphule0710/django-app-nginx
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: django-app-volume-mount
          mountPath: /django-app
      volumes:
      - name: django-app-volume-mount
        persistentVolumeClaim:
          claimName: django-app-pvc