apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: quizstar-portal
data:
  MYSQL_DATABASE: 'mysql-db'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'True'
  MYSQL_HOST: 'mysql-service'
  MYSQL_PORT: '3306'
  REDIS_HOST: 'redis-service'
  REDIS_URL: 'redis://redis-service:6379/0'