apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: quizstar-portal
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: 'ew0KCSJhdXRocyI6IHsNCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsNCgkJCSJhdXRoIjogImMyRm9hV3h3YUhWc1pUQTNNVEE2VTJGb2FXeEFNakF3TXc9PSINCgkJfQ0KCX0NCn0NCg=='