apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: quizstar-portal
type: Opaque
data:
  SECRET_KEY: 'ZGphbmdvLWluc2VjdXJlLXhpKSN2PXclOXJ2bndeXj0wQHZxazc1ZCszeTdpXjV1ZGkkNWZ1bTM3NDcrISQhYWxsDQo='
  MYSQL_USERNAME: 'cm9vdA=='
  MYSQL_PASSWORD: ''