upstream app{
    server app-service:8000;
}

server{
    listen 80 default_server;

    location / {
        proxy_pass http://app;
    }

    location /static/ {
        alias /app/nginx/staticfiles/;
    }
}